### ISSUE TITLE
Right mouse button

### ISSUE THREAD

**Issue by muezis** [manikantareddyd/lyrics_for_music#4]
Hey. Your extension is really good. But there is one problem. Right mouse button. Why it doesn't work? I would like to select the text and perform various actions with it. Also, my browser has a built-in translator that immediately translates the selected text when the right mouse button is clicked, but this doesn't work cause the right mouse button doesn't work. https://imgur.com/a/ENz9dBr Please fix it.

**Comment by manikantareddyd** [comment]
Hi! I have tried to replicate this issue and seems like spotify blocks right click on its entire web player. Right click is working fine in chrome and edge. Can you share a screenshot of the issue :)
